### ISSUE TITLE
License

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/iconfont#3]
https://github.com/joomla-projects/iconfont/blob/4817f1844e6d1cbc3728a73ac36dafaa77afb0e0/config/icon-config.json#L19
https://github.com/joomla-projects/iconfont/blob/4817f1844e6d1cbc3728a73ac36dafaa77afb0e0/config/icons.json#L19

This json value should be an accepted SPDX license (https://spdx.org/licenses/) not just a link to a generic url

example
`  "license": "GPL-2.0-or-later"`

**Comment by kawshar** [comment]
It will be GPL. Sahid will update that.

**Comment by marcodings** [comment]
Licence and README.md adjusted

**Comment by marcodings** [comment]
On the surface we seem safe, unfortunately it seems we need bit more legal coverage @kawshar
The icons seem to originate (partly) from / are also used in icofont.com which is owned by "kawshar" There should be some CLA in place covering the usage towards joomla. 
Joomla will draft a boilerplate CLA to use. tbc

**Comment by kawshar** [comment]
No, the icon were not used from IcoFont. All are custom designed. My designers confirmed me multiple times.

**Comment by marcodings** [comment]
> No, the icon were not used from IcoFont. All are custom designed. My designers confirmed me multiple times.

@brianteeman can you please point out were you think @kawshar is mistaken ?

**Comment by marcodings** [comment]
I guess we'll have to make due, there is no Contributors Agreement.
#2018/005 - Approve Joomla! Contributors Agreement.
#2018/007 - Contributors Agreement is handed back to the Legal Department for further review.
#2018/020 - Remove the existing Code Contributors’ Agreement effective immediately. https://www.opensourcematters.org/organisation/directors/registry-of-motions/265-2018.html

**Comment by brianteeman** [comment]
Personally speaking then we can't accept these fonts and related code as the history shows they are copyrighted

**Comment by kawshar** [comment]
Where do you see copyright? Copyright to Kawshar? Please explain. I am waiting for my flight but your message made me hyper.

**Comment by brianteeman** [comment]
> If I go to Kawshar own repo for this  https://github.com/kawshar/joomla-icon-font  and look at the history I can see numerous references to icofont.com which have all been removed. icofont is cc by 4 as seen here https://icofont.com/license and also in the files that he has edited.
> 
> Further  investigation shows that Kawshar appears to own icofont in which case there may not be a problem as he is able to release his own code under multiple licences.
> 
>  For the avoidance of doubt we really should get Kawshar to sign a formal CLA. Otherwise there is the potential that 
> 1, I am wrong and kawshar is not the owner and does not have the legal authority to change the licence or copyright
> 2. At a future date we have no evidence that these fonts are legally gpl and copyright osm
> 
> Basically imagine the scenario where kawshar is no longer the owner of the company and/or his github repository is deleted. Our repository has no history (again!!!) so we have no proof that he made the changes to the copyright code and changed its licence.

**Comment by brianteeman** [comment]
strange that just after i posted about icofont you did a pull request to change the remaining references to icofont and added your own copyright statement
![image](https://user-images.githubusercontent.com/1296369/67693554-cc098800-f999-11e9-9750-af328d7d77bc.png)

And that usage restriction " use it in any legal personal, organizational or commercial project." makes it non-free

**Comment by kawshar** [comment]
I am telling you again that the icons are custom designed. And, icofont is my website and all icons are mine too. We just used some nodejs script only.

And, icofont icons are also under cc license.

Note: for the final time, icons are created here and there is nothing wrong with the license.

**Comment by marcodings** [comment]
> strange that just after i posted about icofont you did a pull request to change the remaining references to icofont and added your own copyright statement

Nothing strange about that it was discussed way prior to your remark here and set in motion

**Comment by marcodings** [comment]
> And that usage restriction " use it in any legal personal, organizational or commercial project." makes it non-free
@brianteeman So how would you phrase it as i'm sure you understand the intentions over the actual wording. Remember that we are not all native speakers and we do not neccesarilly want to pay lawyers to do the work.

**Comment by brianteeman** [comment]
@marcodings I refer to my original comment 4 hours ago

@kawshar cc-by-attribution licence can not be used

**Comment by brianteeman** [comment]
@marcodings look at the similar sentence for Joomla. Oh wait there isn't one because you can't have any restrictions on gpl software.

**Comment by marcodings** [comment]
> @marcodings I refer to my original comment 4 hours ago
Don't know what you want to say with this, i have been discussing this with kawshar since 9 this morning. But does it matter who brought it up first, or does it matter we find a non bureaucratic solution to a non-existing problem

**Comment by kawshar** [comment]
@brianteeman you clearly not checking my comment, right? I said we designed the icons which are gpl. Those are not icofont’s assets.

**Comment by marcodings** [comment]
> 
> 
> @marcodings look at the similar sentence for Joomla. Oh wait there isn't one because you can't have any restrictions on gpl software.

So you could have said something like "GPL licence attribution suffices" no need for the "elaboration". That would be a constructive approach, contrary to how you are snide way of voicing it now.

**Comment by brianteeman** [comment]
@marcodings i give up. I tried to do this quietly and privately with the relevant stakeholders within joomla. but you are too ------ to understand how to use git to maintain history, why it is essential for the integrity of joomla to have a clear audit trail and most importantly when it has been shown that the code has been changed to remove/change a copyright it is even more essential that joomla is legally protected as we cannot rely on this being a good faith commit. The fact that you don't understand what the GPL means is seriously concerning for anyone who has been involved in open source software for so long.

unsubscribed - do what you want - you will do anyway

**Comment by marcodings** [comment]
@brianteeman you seem to have no interest in trying to keep up with facts. It must be a sign of the times where people just shout unfounded opinions. 
As for example the history thing is mentioned here https://github.com/joomla-projects/j4adminui/issues/12#issuecomment-546854431 and solutions were discussed with J!4 release lead and production department coordinator.

**Comment by marcodings** [comment]
@brianteeman 
> but you are too ------ to understand

Such remarks are not needed and insulting

**Comment by brianteeman** [comment]
as were your comments

**Comment by C-Lodder** [comment]
I know Joomla follows GPL-2, however I definitely think this should be MIT.
